export default {
  onViewportChange: 'viewport:changed',
  onRegionClick: 'region:clicked',
  onMarkerClick: 'marker:clicked',
  onRegionSelected: 'region:selected',
  onMarkerSelected: 'marker:selected',
  onRegionTooltipShow: 'region.tooltip:show',
  onMarkerTooltipShow: 'marker.tooltip:show',
  onLoaded: 'map:loaded',
  onDestroyed: 'map:destroyed',
  onRegionOver: 'map: onRegionOver',
  onRegionOut: 'map:onRegionOut',
  onMarkerOver: 'map:onMarkerOver',
  onMarkerOut: 'map:onMarkerOut',
}